/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI */

#ifndef _Included_DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI
#define _Included_DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI
 * Method:    getDistance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI_getDistance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
