/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DomFaryna_FiveGuysOneRobot_Sensors_SideFinderJNI */

#ifndef _Included_DomFaryna_FiveGuysOneRobot_Sensors_SideFinderJNI
#define _Included_DomFaryna_FiveGuysOneRobot_Sensors_SideFinderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_SideFinderJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_SideFinderJNI_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_SideFinderJNI
 * Method:    getDistance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_SideFinderJNI_getDistance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
