/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI */

#ifndef _Included_DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI
#define _Included_DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI
 * Method:    calibrate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI_calibrate
  (JNIEnv *, jobject);

/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI
 * Method:    getRawGyro
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI_getRawGyro
  (JNIEnv *, jobject);

/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI
 * Method:    getRawAcc
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI_getRawAcc
  (JNIEnv *, jobject);

/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI
 * Method:    getRawMag
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_ImuJNI_getRawMag
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
