/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI */

#ifndef _Included_DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI
#define _Included_DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DomFaryna_FiveGuysOneRobot_Sensors_RangeFinderJNI_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
